### PR TITLE
feat: Report stale screenshots

### LINKED ISSUE #334: Ability to cleanup outdated screens
Hi!
Is there is any ability to cleanup all screenshots tests for which were removed/moved to another suite?

### PR DESCRIPTION
**Pull request by Hypnosphi**
Fixes #334

### CODE REVIEW

**Comment by DudaGod** [comment]
Hello.

To my mind it should be implemented as a separate command (for example - `npx hermione clean-screenshots`).  We already had an attempt to implement this but did not complete it to the end

**Comment by Hypnosphi** [comment]
@DudaGod how can I get state names without running all the tests?

**Comment by DudaGod** [comment]
> how can I get state names without running all the tests?

You need to implement custom runner in order to read all tests with a redefined `assertView` command. In this redefined command you will be able to collect all image states. Custom runner should not launch browsers. It's not an easy task but this is how it should be done.

**Comment by Hypnosphi** [comment]
> Custom runner should not launch browsers

Then it's quite likely that tests won't reach the `assertView` stage

**Comment by DudaGod** [comment]
> Then it's quite likely that some tests won't even reach the assertView stage, e.g. if they wait for some condition before it

If we overwrite all commands to return `Promise.resolve()` then `assertView` will be reach in all tests.

**Comment by DudaGod** [comment]
Hello.

Ability to remove unused screens is already implemented in html-reporter@8.4.2. More info about this command is here - https://github.com/gemini-testing/html-reporter#remove-unused-screens.

I close it, thank you.

**Pull request closed without merging**
