### PR TITLE
Fix for example in quick start section in Readme

### PR DESCRIPTION
**Pull request by vitkarpov**
Hi there,

love you're doing here, thanks! :)

Found that example in quick start section doesn't work. Actually there's a couple of problems here:

- `.search2__input input -> .search2__input .input__control` (there're two inputs actually, so webdriver fails on trying to pick up the right one)

```
✘ Error: invalid element state: Element is not currently interactable and may not be manipulated
```

- `waitForVisible` (the page needs some time after search request)
- `z-entity-card__title` doesn't seem exist anymore
- changed `com -> ru` to make sure the language is always the same (com can redirect to ru)

**UPD**

Changed test: goes to github page of hermione and find the title

### CODE REVIEW

**Comment by sipayRT** [comment]
we can replace it to the github.com :)

**Comment by vitkarpov** [comment]
WAT? :)

**Comment by j0tunn** [comment]
Жека предлагает заменить тест страницы Яндекса на какую-нибудь проверку на `github.com`. Инструмент внешний, на русском мы в нем не пишем (ну кроме PR'ов и issues :) )

**Comment by sipayRT** [comment]
/merged ;)
thx!

**Comment by vitkarpov** [comment]
🎆 😎

**Pull request merged**
